# Generated by Django 3.0.7 on 2020-07-08 21:36

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('author', models.CharField(default='', max_length=200)),
                ('grade_level', main.models.IntegerRangeField()),
                ('dt', models.DateTimeField(default=datetime.datetime.now, verbose_name='DateTime Published')),
                ('content', models.TextField()),
            ],
        ),
    ]
