# Generated by Django 3.0.7 on 2020-07-09 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200708_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
