# Generated by Django 3.0.7 on 2020-07-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200708_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='subjects',
            field=models.ManyToManyField(related_name='potential_tutors', to='main.Category'),
        ),
    ]
