# Generated by Django 3.0.7 on 2020-07-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='subjects',
        ),
    ]
