# Generated by Django 3.0.7 on 2020-07-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_tutor_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='subjects',
            field=models.ManyToManyField(related_name='potential_tutors', to='main.Subject'),
        ),
    ]
