# Generated by Django 3.0.7 on 2020-08-04 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tutor_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='subject',
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='subsubjects', to='main.Category', verbose_name='Category'),
        ),
    ]
