# Generated by Django 3.0.7 on 2020-08-04 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200804_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Subject', verbose_name='Category'),
        ),
    ]
