# Generated by Django 3.0.7 on 2020-08-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_request_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='slug',
            field=models.TextField(default='1596747750.075731'),
        ),
    ]
