# Generated by Django 3.0.7 on 2020-08-10 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_request_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='tutor_accepted',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Tutor'),
        ),
        migrations.AlterField(
            model_name='request',
            name='slug',
            field=models.TextField(default='1597083333.037298'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_reverse', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
