# Generated by Django 3.0.7 on 2020-08-13 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200810_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='slug',
            field=models.TextField(default='1597294174.06709'),
        ),
        migrations.AlterField(
            model_name='request',
            name='tutor_accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Tutor'),
        ),
    ]
