# Generated by Django 3.0.7 on 2020-08-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200812_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='chosen_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='slug',
            field=models.TextField(default='1597297179.725269'),
        ),
    ]
